#Construct HSMM Class
num.columns <- ncol(HSMM_expr_matrix)
name.columns <- colnames(HSMM_expr_matrix)
num.rows <- nrow(HSMM_expr_matrix)
name.rows <- rownames(HSMM_expr_matrix)
HSMM_sample_sheet <- matrix(nrow = num.columns, ncol= 0)
rownames(HSMM_sample_sheet) <- c(name.columns)
HSMM_sample_sheet <- data.frame(HSMM_sample_sheet)
HSMM_gene_annotation <- matrix(nrow = num.rows, ncol= 0)
rownames(HSMM_gene_annotation) <- c(name.rows)
HSMM_gene_annotation <- data.frame(HSMM_gene_annotation)
rm(name.rows)
rm(name.columns)
rm(num.rows)
rm(num.columns)
pd <- new("AnnotatedDataFrame", data = HSMM_sample_sheet)
fd <- new("AnnotatedDataFrame", data = HSMM_gene_annotation)
HSMM <- newCellDataSet(as.matrix(HSMM_expr_matrix), phenoData = pd, featureData = fd)
rm(pd)
rm(fd)